export const MAIN_COLOR = '#2c2c47'
export const MAIN_COLOR_ON_HOVER = '#3d3d63'
export const MAIN_COMPONENT_COLOR = '#46466E'
export const INPUT_COLOR = '#BDBDD7'
export const MAIN_TEXT_COLOR = '#dd105e'