# Generated by Django 4.0.6 on 2022-12-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatswap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=20)),
                ('upVotes', models.IntegerField()),
                ('downVotes', models.IntegerField()),
            ],
        ),
    ]
