# Generated by Django 4.0.6 on 2022-12-29 06:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatswap', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 6, 25, 56, 181199, tzinfo=utc), verbose_name='Sent @'),
            preserve_default=False,
        ),
    ]
