// export const MAIN_COLOR = "#0C134F";
// export const MAIN_COLOR_ON_HOVER = "#111a6c";
// export const MAIN_COMPONENT_COLOR = "#1D267D";
// export const INPUT_COLOR = "#D4ADFC";
// export const MAIN_TEXT_COLOR = "#5C469C";
// export const BANNER_COLOR = "#080c32";
// export const DISABLED_INPUT_COLOR = "#9B7DB9";

export const MAIN_COLOR = "#11009E";
export const MAIN_COLOR_ON_HOVER = "#1600E0";
export const MAIN_COLOR_DISABLED = "#2C1FA0";
export const MAIN_COMPONENT_COLOR = "#4942E4";
export const INPUT_COLOR = "white";
export const SECONDARY_INPUT_COLOR = "#C4B0FF";
export const MAIN_TEXT_COLOR = "#8696FE";
export const BANNER_COLOR = "#0C007A";
export const DISABLED_INPUT_COLOR = "#8d8db3";
export const ACTIVE_COLOR = "#FFFFFF";
export const LINK_COLOR = "#FFFFFF";
